// Test definitions. Do NOT edit this file!

#include <tuple>

#define CATCH_CONFIG_MAIN // defines main() automatically
#include "catch.hpp"

#include "student.hpp" // student implementations

// =====================
// tests for exercise 1
// ---------------------

TEST_CASE("Ex1", "[example]")
{
    REQUIRE(yearChecker(2021)==1);
    REQUIRE(ageChecker(2022)==1);
    REQUIRE(ageChecker(2023)==0);
    REQUIRE(ageChecker(2018)==1);
    REQUIRE(ageChecker(2017)==0);
    REQUIRE(ageChecker(-2017)==0);    
}

